#!/bin/bash

Pyano () {
	cd /home/junshern/Scripts/Pyano/dev/
	echo "Starting Pyano..."
	sudo python main.py 
}

# Script to launch audio servers for music-making
case $1 in
	start )
		echo "Please select an audio device: (enter card number)"
		aplay -l | grep card
		read -p "> " hw
		echo "You selected HW:$hw"

		# Start fluidsynth
		echo
		echo "Starting Fluidsynth..."
		fluidsynth --server --no-shell --audio-driver=alsa \
			--reverb=0 --gain=0.8 \
			/usr/share/sounds/sf2/FluidR3_GM.sf2 \
			&>/tmp/fluidsynth.out &
		sleep 1

		# Launch Pyano in new terminal
		echo
		Pyano

		;;
	stop )
		wmctrl -F -c Onion
		killall sooperlooper
		killall slgui
		killall fluidsynth
		killall jackd
		echo "Thank you for the music."
		;;
	* )
		echo "Please specify start or stop..."
		;;
esac

